### ISSUE TITLE
farEnd language confusing

### ISSUE THREAD

**Issue by tschady** [finos/voice-metadata-standard#9]
I would suggest that `farEnd` refer to the device, and `counterparty` refer to the person that answers the call.

**Comment by leop-tcto** [comment]
We will need to come up with the right word. In the trading world some lines such as hoots are always up so that counterparty may be more than one person listening to that hoot.

**Comment by kemmiso** [comment]
to date we have used sourceaddress and destination address does hoot have a direction? Even if nailed up?

**Comment by leop-tcto** [comment]
Apologies in advance for this very long comment:

The intent was to think if these connections not just as traditional telephone connections where you make a call from one system to the other, but to think of them more as a voice chat room. The connection (or line) itself is really a voice chat room. The connection connects two firms where each firm may have one or more users in that voice chat room. These metadata standarda should capture this. I would think that future integrations with IM systems will require the same kind of idea.

Present day traditional trading system only know they are connecting Firm A to Firm B using a connection.  Future trading systems will also know the names of users on each end of the connection. I wanted to assure the meta data standard can capture all of this if we agree. Whether the connection is a hoot, ringdown, shoutdown does not matter because all of this still applies. It will even apply to a dialtone type call if more than one person barges in on either side of an ongoing call.

**Comment by kemmiso** [comment]
so does sourceaddress and destinationaddress not work in all such scenarios? Once you add in the direction you can deduce which is the far end. this then works for IM and so forth.

**Comment by leop-tcto** [comment]
@kemmiso yes sourceaddress and destinationaddress should work. I just wanted to be very clear as to what the connection looks like.

**Comment by vitorespindola** [comment]
Do we need to define the participants as farEnd or destination? Just renaming participant object fields(eg. rename farEndName to name) did not work as well? Maybe we just need to store the source participant(as a participant object) outside of **callRecord.participants** field or add a flag to it on the  **callRecord.participants** field. The source is also a participant in the call.

Also, we need to find way to don't let this be confused with **userInfo** field which relates to the recordFile itself(the point of view of the recording file). Shall we move **userInfo** to the recordFile object?

**Comment by leop-tcto** [comment]
Let me start with **userInfo**. This is the information about which user owns both the call record and the call recording for the referenced metadata. It is not just for the recording.

**farEnd** and **nearEnd** were originally designed to capture the fact that calls are between two firms. So I am not sure that **sourceAddress** and **destinationAddress** captures this or not. **nearEnd** is my firm. **farEnd** is the other firm I am calling. If the call is internal then there is no **farEnd**. I agree that all the names are confusing. So let me attempt the following definitions:
**sourceAddress - is the caller?
**destinationAddress - is the callee? (Sometime you don't know the person sometimes you do?)
**nearEnd - is the firm of the caller (and all the people who are also listening on the calling side if it is a hoot)
**farEnd - is the firm of the calleree (and all the people who are also listening on the callee side if it is a hoot)

I need some more time to look at what we have and follow up this comment with a JSON example.

**Comment by kemmiso** [comment]
We suggest it can be deduced from the user's participation. IE are they the initiator of the call if so they are the source user and the far side are in effect the destinations.  #49 I shows this.
